version: '3'
services:
  docker-postgres:
    restart: always
    container_name: docker-postgres
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  running-app:
    restart: on-failure
    build: ./
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      WAIT_HOSTS: postgres:5432
    depends_on:
      - docker-postgres
