version: '3'
services:
  docker-mongodb:
    restart: always
    container_name: docker-mongodb
    image: mongo:latest
    volumes:
      - ./database:/data/db
    ports:
      - "27017:27017"

  running-app:
    restart: on-failure
    build: ./
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      WAIT_HOSTS: mongo:27017
    depends_on:
      - docker-mongodb
