version: '3.1'
services:
  app:
    container_name: app-basededatos-unlp
    image: app-basededatos-unlp
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbmysql
  dbmysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=basededatosunlp
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
