spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/basededatosunlp
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    mapping-resources:
      - mappings/User.hbm.xml
      - mappings/Company.hbm.xml
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
