spring:
  application:
    name: basededatos-unlp
  datasource:
    url: jdbc:mysql://docker-mysql:3306/basededatosunlp?serverTimezone=UTC
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    mapping-resources:
      - mappings/User.hbm.xml
      - mappings/RunningApp.hbm.xml
      - mappings/Run.hbm.xml
      - mappings/Location.hbm.xml
    show-sql: false
    hibernate.ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
