spring:
  datasource:
    url: jdbc:mysql://localhost:3306/basededatosunlp?serverTimezone=UTC
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    mapping-resources:
      - mappings/User.hbm.xml
      - mappings/Company.hbm.xml
      - mappings/Run.hbm.xml
      - mappings/Location.hbm.xml
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
